global_frame: map
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
rolling_window: false
width: 5.0
height: 10.0
origin_x: -2.5
origin_y: -5.0
resolution: 0.05
transform_tolerance: 0.3

plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

footprint: [[-0.124, -0.096], [0.124, -0.096], [0.124, 0.096], [-0.124, 0.096]]

obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  track_unknown_space: false
  combination_method: 1
  observation_sources: laser_scan
  laser_scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: 0.0
    max_obstacle_height: 2.0

inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0
  inflation_radius: 0.0